// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqxjMhe0IIyTWxK-gfWdTAHLEvaALpWiM',
    appId: '1:184642886999:web:55258ec770675dcc487212',
    messagingSenderId: '184642886999',
    projectId: 'cinevault-ali-ozcan-karol',
    authDomain: 'cinevault-ali-ozcan-karol.firebaseapp.com',
    storageBucket: 'cinevault-ali-ozcan-karol.firebasestorage.app',
    measurementId: 'G-QVECPSR6SF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbLzygHjiW-5sRU1Om9pYZlDRXdpwNzsI',
    appId: '1:184642886999:android:30a7400be22ae4a7487212',
    messagingSenderId: '184642886999',
    projectId: 'cinevault-ali-ozcan-karol',
    storageBucket: 'cinevault-ali-ozcan-karol.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuJpYuflnKNX93lN2w10jLqdKqm1l65Nw',
    appId: '1:184642886999:ios:62e4dffa79359aa8487212',
    messagingSenderId: '184642886999',
    projectId: 'cinevault-ali-ozcan-karol',
    storageBucket: 'cinevault-ali-ozcan-karol.firebasestorage.app',
    iosBundleId: 'com.example.flutterMovieTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuJpYuflnKNX93lN2w10jLqdKqm1l65Nw',
    appId: '1:184642886999:ios:62e4dffa79359aa8487212',
    messagingSenderId: '184642886999',
    projectId: 'cinevault-ali-ozcan-karol',
    storageBucket: 'cinevault-ali-ozcan-karol.firebasestorage.app',
    iosBundleId: 'com.example.flutterMovieTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqxjMhe0IIyTWxK-gfWdTAHLEvaALpWiM',
    appId: '1:184642886999:web:7fd7c415ea635ce1487212',
    messagingSenderId: '184642886999',
    projectId: 'cinevault-ali-ozcan-karol',
    authDomain: 'cinevault-ali-ozcan-karol.firebaseapp.com',
    storageBucket: 'cinevault-ali-ozcan-karol.firebasestorage.app',
    measurementId: 'G-VZT54DQMZ4',
  );
}
